# This workflow builds a CMake C/C++ project on macOS, Windows, and Linux.
name: CMake Multi-Platform CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build (${{ matrix.os }}, ${{ matrix.build-type }})

    strategy:
      # Should set to true if you want to stop the build on the first failure
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        build-type: [Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Show Matrix & Runner
        shell: bash
        run: |
          echo "matrix.os = ${{ matrix.os }}"
          echo "runner.os = $RUNNER_OS"
          echo "Runner: $RUNNER_NAME"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies - macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew untap aws/tap 2>/dev/null || true
          brew install opencv libheif exiv2

      - name: Install dependencies - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopencv-dev \
            libheif-dev \
            libexiv2-dev \
            libheif-examples \
            libheif-plugin-x265 \
            libheif-plugin-libde265 \
            pkg-config \
            python3

          echo "=== libheif ==="
          dpkg -l | grep libheif || true

          echo "=== HEIF encoder ==="
          command -v heif-enc || true

          echo "=== heif-enc version ==="
          heif-enc --version || true

          echo "=== libheif codecs ==="
          heif-enc --list-encoders || true

      - name: Configure CMake - macOS/Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then
            CXX=clang++
          else
            CXX=g++
          fi

          cmake \
            -S "${{ github.workspace }}" \
            -B "${{ github.workspace }}/build" \
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
            -DCMAKE_CXX_COMPILER="$CXX" \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_CXX_EXTENSIONS=OFF

      - name: Diagnose Visual Studio
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"

          Write-Host "=== vswhere: $vswhere"
          & $vswhere `
            -latest `
            -products * `
            -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            -property installationPath

          Write-Host "=== C++ compiler files:"
          Get-ChildItem `
            "C:\Program Files\Microsoft Visual Studio\18" `
            -Filter cl.exe `
            -Recurse `
            -ErrorAction SilentlyContinue |
            Select-Object -ExpandProperty FullName

      - name: Setup vcpkg and Binary Cache - Windows
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '94a541197763a4f449a1b91478df48c0584a6256'
          vcpkgJsonGlob: 'vcpkg.json'

      # Config CMake (It triggers vcpkg to read vcpkg.json & install packages)
      - name: Config CMake - Windows
        if: runner.os == 'Windows'
        run: >
          cmake -B build -S "${{ github.workspace }}"
          -DCMAKE_TOOLCHAIN_FILE="$env:RUNVCPKG_VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
          -DVCPKG_TARGET_TRIPLET=x64-windows
          -DVCPKG_MANIFEST_MODE=ON
          -DVCPKG_MANIFEST_DIR="${{ github.workspace }}\windows"

      - name: Check vcpkg_installed - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $manifestDir = "$env:GITHUB_WORKSPACE\windows"
          $vcpkgExe = "$env:RUNVCPKG_VCPKG_ROOT\vcpkg.exe"
          $vcpkgInstalled = "$env:GITHUB_WORKSPACE\build\vcpkg_installed\x64-windows"

          Write-Host "=== Installed Packages in Manifest Mode:"
          & $vcpkgExe list --x-manifest-root="$manifestDir"

          Write-Host "=== libheif share files:"
          Get-ChildItem -Recurse "$vcpkgInstalled\share\libheif" -ErrorAction SilentlyContinue

          Write-Host "=== LIBHEIF_VERSION in heif_version.h"
          $header = Get-Content "$vcpkgInstalled\include\libheif\heif_version.h"
          $header | Select-String "LIBHEIF_VERSION"

          Write-Host "=== libheif portfile in vcpkg repo:"
            $portPath = "$env:RUNVCPKG_VCPKG_ROOT\ports\libheif"
            if (Test-Path $portPath) {
                Get-ChildItem "$portPath" -Recurse | Select-Object FullName
            } else {
                Write-Host "Portfile not found at $portPath"
            }

      - name: Build
      # Cross-platform: one-line cmake to avoid syntax issue between Unix and Windows
        run: cmake --build "${{ github.workspace }}/build" --config ${{ matrix.build-type }} --parallel

      - name: Add vcpkg bin to PATH - Windows
        if: runner.os == 'Windows'
        run: echo "C:\vcpkg\installed\x64-windows\bin" >> $env:GITHUB_PATH

      - name: Test
        working-directory: ${{ github.workspace }}/build
        # Cross-platform: one-line ctest to avoid syntax issue between Unix and Windows
        run: ctest --build-config ${{ matrix.build-type }} --output-on-failure
