# Build wheels on macOS, Windows, and Linux.
name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # <--- Enables manual trigger button

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Runs natively on Ubuntu, Windows, and macOS runners
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel

      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibuildwheel-${{ matrix.os }}
          path: ./wheelhouse/*.whl
